name: ${project.name}
main: net.cyberflame.tridentsafety.Main
version: ${project.version}
description: TridentSafety
website: https://cyberfla.me/
author: CyberFlame
api-version: 1.17
load: POSTWORLD
