name: TridentSafety
main: net.cyberflame.tridentsafety.Main
version: ${project.version}
description: Safeties for tridents
website: https://cyberfla.me/
author: CyberFlame
api-version: 1.17
load: POSTWORLD
